# Generated by Django 3.1.5 on 2021-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Логин пользователя')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия пользователя')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество пользователя')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
